#!/usr/bin/env python3
"""Generate ap_placeholders.cfg with placeholder PART blocks for AP tech tree integration.

Each placeholder uses the AP model and is hidden from the normal tech tree
(TechRequired = inaccessable). PlaceholderManager.cs swaps these into tech nodes at
runtime to show scouted AP items.
"""

import os
import sys

NUM_PLACEHOLDERS = 80
OUTPUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "..", "assets", "ap_placeholders.cfg")

TEMPLATE = """\
PART
{{
    name = ap_placeholder_{num:03d}
    module = Part
    author = KSP-Archipelago

    MODEL
    {{
        model = KSPArchipelago/Models/AP
    }}

    rescaleFactor = 1

    TechRequired = inaccessable
    entryCost = 0
    cost = 0
    category = none
    subcategory = 0
    title = AP Item
    manufacturer = Archipelago
    description = An Archipelago multiworld item.

    attachRules = 0,0,0,0,0
    mass = 0.001
    dragModelType = default
    maximum_drag = 0.1
    minimum_drag = 0.1
    angularDrag = 1
    crashTolerance = 10
    maxTemp = 1200
    bulkheadProfiles = srf
}}
"""


def main():
    parts = []
    for i in range(1, NUM_PLACEHOLDERS + 1):
        parts.append(TEMPLATE.format(num=i))

    header = "// Auto-generated by generate_placeholders.py — do not edit by hand.\n\n"
    with open(OUTPUT, "w") as f:
        f.write(header)
        f.write("\n".join(parts))

    print(f"Wrote {NUM_PLACEHOLDERS} placeholder parts to {OUTPUT}")


if __name__ == "__main__":
    main()
